dist: trusty

language: node_js
node_js:
  - 12.20.0


install:

  - cp package.dev.json package.json
  - rm -rf node_modules
  - rm -rf package-lock.json
  - rm -rf package.json
  - cp package.dev.json package.json
  - npm install
  - npm run build-file-select
  - npm run build-jsdraw-wrapper
  - npm run build-ketcher-wrapper
  - cp package.real.json package.json
  - npm install --legacy-peer-deps
  - npm install webpack
  - npm i --save webpack-sources --legacy-peer-deps
  - export NODE_OPTIONS="--max-old-space-size=8192"
script:
  - npm run build:fda:prod
after_success:
  - ls
  - zip -r test.zip dist
  - ls
  - cp test.zip ../
  - ls
before_deploy:
  # Set up git user name and tag this commit
  - echo "before deploy"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key: ${GIT_ACCESS_TOKEN}
  file: "../test.zip"
  skip_cleanup: true
  on:
    all_branches: true
