dist: trusty

language: node_js
node_js:
  - 14.17.0


install:

  - cp package.dev.json package.json
  - rm -rf node_modules
  - rm -rf package-lock.json
  - rm -rf package.json
  - cp package.dev.json package.json
  - npm install
  - npm run build-file-select
  - npm run build-jsdraw-wrapper
  - npm run build-ketcher-wrapper
  - cp package.real.json package.json
  - npm install --legacy-peer-deps
  - npm install webpack
  - npm i --save webpack-sources --legacy-peer-deps
  - export NODE_OPTIONS="--max-old-space-size=8192"
script:
  - npm run build:fda:prod
after_success:
  - if [ $TRAVIS_BRANCH = 'import_merge' ]; then bash travisScript.sh; else echo "Not a branch set to push"; fi

