name: Lint Code

on: [push, pull_request]

jobs:
  lint:
    name: Linting code
    runs-on: ubuntu-latest
    
    steps:
      - name: TSLint checks
        uses: mooyoul/tslint-actions@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pattern: '*.ts;*.spec.ts-'
