name: Lint Code

on: [pull_request]

jobs:
  lint:
    name: Linting code
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Prepare
        run: npm ci
      - name: Lint
        uses: mooyoul/tslint-actions@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pattern: '*.ts;*.spec.ts-'
